import java.util.Scanner;

class DiffieHellman {

    // Power function to return value of a ^ b mod P
    private static long power(long a, long b, long p) {
        long result = 1;
        for (int i = 0; i < b; i++) {
            result = (result * a) % p;
        }
        return result;
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        // Taking user input for P and G
        System.out.print("Enter a prime number P: ");
        long P = scanner.nextLong();

        System.out.print("Enter a primitive root G: ");
        long G = scanner.nextLong();

        // Alice's private key
        System.out.print("Enter private key for Alice (a): ");
        long a = scanner.nextLong();
        long x = power(G, a, P); // Public key generated by Alice

        // Bob's private key
        System.out.print("Enter private key for Bob (b): ");
        long b = scanner.nextLong();
        long y = power(G, b, P); // Public key generated by Bob

        // Generating the secret key after key exchange
        long ka = power(y, a, P); // Secret key for Alice
        long kb = power(x, b, P); // Secret key for Bob

        // Display results
        System.out.println("\nPublic Key for Alice (x): " + x);
        System.out.println("Public Key for Bob (y): " + y);
        System.out.println("\nSecret key for Alice: " + ka);
        System.out.println("Secret key for Bob: " + kb);

        // Closing scanner
        scanner.close();
    }
}

